#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GeoQuiz.Resource", IsApplication=true)]

namespace GeoQuiz
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int answerTextView = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int api_level_textview = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int cheat_button = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int false_button = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int next_button = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int previous_button = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int showAnswerButton = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int true_button = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int txtQuestion = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_cheat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_quiz = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int cheat_button = 2130968588;
			
			// aapt resource value: 0x7f040005
			public const int correct_toast = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int false_button = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int incorrect_toast = 2130968582;
			
			// aapt resource value: 0x7f04000f
			public const int judgment_toast = 2130968591;
			
			// aapt resource value: 0x7f040004
			public const int next_button = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int question_africa = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int question_americas = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int question_asia = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int question_mideast = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int question_oceans = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int question_text = 2130968577;
			
			// aapt resource value: 0x7f04000e
			public const int show_answer_button = 2130968590;
			
			// aapt resource value: 0x7f040002
			public const int true_button = 2130968578;
			
			// aapt resource value: 0x7f04000d
			public const int warning_text = 2130968589;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
