#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RemoteControl.Resource", IsApplication=true)]

namespace RemoteControl
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bar_patch = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_shape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_shape_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_shape_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_shape_shadowed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_text_color = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int remote_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int window = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int window_patch = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int deleteButton = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int enterButton = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int fragmentContainer = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int fragment_remote_control_selectedTextView = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int fragment_remote_control_tableLayout = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int fragment_remote_control_workingTextView = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int zeroButton = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_fragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int button_row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_remote_control = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int RemoteButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int SpecialButton = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
