#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Feeder.Resource", IsApplication=true)]

namespace Feeder
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Feeder.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_check_off = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_check_on = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int addFeedMenu = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int addUrlButton = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int feedListItemListView = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int feedListView = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int feedUrlTextView = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int fragmentContainer = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int progressBar = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int updateFeedItemMenu = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int urlEditText = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int webView = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_fragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_add_feed = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_feed_list = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_feed_list_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_post_page = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu_feed_list = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menu_feed_list_item = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int addFeed = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int addUrl = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int autoUpdate = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int feedUrl = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
